# Use action to approve the migration
name: Approve Migration with Action

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.up.sql"

jobs:
  bytebase-approve-migration:
    runs-on: ubuntu-latest
    env:
      BYTEBASE_URL: "https://bytebase-ci.zeabur.app"
      SERVICE_ACCOUNT: "ci@service.bytebase.com"
    name: Approve Migration
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Login to Bytebase
          id: login
          uses: ./.github/actions/login
          with:
            url: ${{ env.BYTEBASE_URL }}
            service_account: ${{ env.SERVICE_ACCOUNT }}
            service_account_key: ${{ secrets.BYTEBASE_PASSWORD }}
        - name: Approve issue
          id: approve
          uses: ./.github/actions/approve-issue
          with:
            url: ${{ env.BYTEBASE_URL }}
            token: ${{ steps.login.outputs.token }}
            issue_uid: 114
            comment: "Approved by CI"