name: Check Migration status

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.up.sql"

jobs:
  bytebase-check-migration-status:
    runs-on: ubuntu-latest
    env:
      PROJECT: "example"
      ISSUE_TITLE: "[${{ github.repository }}#${{ github.event.number }}] ${{ github.event.pull_request.title }}"
    name: Check Migration
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Bytebase
        id: login
        uses: ./.github/actions/login
        with:
          url: ${{ secrets.BYTEBASE_URL }}
          service-account: ${{ secrets.BYTEBASE_SERVICE_ACCOUNT }}
          service-account-key: ${{ secrets.BYTEBASE_PASSWORD }}
      - name: Get issue
        id: get
        uses: ./.github/actions/get-issue
        with:
          url: ${{ secrets.BYTEBASE_URL }}
          token: ${{ steps.login.outputs.token }}
          headers: '{"Accept-Encoding": "deflate, gzip"}'
          project-id: ${{ env.PROJECT }}
          title: ${{ env.ISSUE_TITLE }}
