name: Approve Migration

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.up.sql"

jobs:
  bytebase-approve-migration:
    runs-on: ubuntu-latest
    env:
      PROJECT: "example"
      ISSUE_TITLE: "[${{ github.repository }}#${{ github.event.number }}] ${{ github.event.pull_request.title }}"
    name: Approve Migration
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Bytebase
        id: login
        uses: ./.github/actions/login
        with:
          url: ${{ secrets.BYTEBASE_URL }}
          service-account: ${{ secrets.BYTEBASE_SERVICE_ACCOUNT }}
          service-account-key: ${{ secrets.BYTEBASE_PASSWORD }}
      - name: Get issue
        id: get
        uses: ./.github/actions/get-issue
        with:
          url: ${{ secrets.BYTEBASE_URL }}
          token: ${{ steps.login.outputs.token }}
          project-id: ${{ env.PROJECT }}
          title: ${{ env.ISSUE_TITLE }}
      - name: Extract issue uid
        id: extract
        run: |
          issue_uid=$(echo '${{ steps.get.outputs.issue }}' | jq -r '.uid')
          echo "issue_uid=${issue_uid}" >> $GITHUB_OUTPUT
      - name: Approve issue
        id: approve
        uses: ./.github/actions/approve-issue
        if: steps.get.outputs.issue
        with:
          url: ${{ secrets.BYTEBASE_URL }}
          token: ${{ steps.login.outputs.token }}
          headers: '{"Accept-Encoding": "deflate, gzip"}'
          project-id: ${{ env.PROJECT }}
          issue-uid: ${{ steps.extract.outputs.issue_uid }}
          comment: "Approved by CI"
