# Use action to create the migration
name: Create Migration with Action

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.up.sql"

jobs:
  bytebase-approve-migration:
    runs-on: ubuntu-latest
    env:
      API_ENDPOINT: "https://bytebase-ci.zeabur.app/v1"
      SERVICE_ACCOUNT: "ci@service.bytebase.com"
    name: Approve Migration
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Login to Bytebase
          id: login
          uses: ./.github/actions/login
          with:
            endpoint: ${{ env.API_ENDPOINT }}
            service_account: ${{ env.SERVICE_ACCOUNT }}
            service_account_key: ${{ secrets.BYTEBASE_PASSWORD }}
        - name: Create issue
          id: create
          uses: ./.github/actions/create-issue
          with:
            endpoint: ${{ env.API_ENDPOINT }}
            token: ${{ steps.login.outputs.token }}
            project_id: "example"
            database: "instances/prod-instance/databases/example"
            statement: "CREATE TABLE example (id INT PRIMARY KEY, name VARCHAR(255));"
            title: "[${{ github.repository }}#${{ github.event.number }}] ${{ github.event.pull_request.title }}"
            description: "Triggered by ${{ github.event.repository.html_url }}/pull/${{ github.event.number }} ${{ github.event.pull_request.title }}"